name: PressurePush
main: com.gmail.munjavk.pressurepush.PressurePush
version: 1.2
author: euro1988, CullanP
commands:
  ppload:
    description: Reloads the config for PressurePush
    usage: /ppload
  ppcreate:
    description: Toggleable on or off
    usage: /ppcreate
  pressurepush:
    description: Gives you a detailed information about the plugin and its commands
    usage: /pressurepush
    aliases: [pp]
  ppset:
    description: Sets the plate strength,up
    usage: /ppset
permissions:
  pp.*:
    default: op
    description: Give players with op everything by default
  pp.use:
    default: true
    description: Give players with op everything by default