## PressurePush by euro1988 ##
## http://dev.bukkit.org/bukkit-plugins/pressurepush/ ##
## The values you input in Strength and Up are decimal numbers, eg. 1.5 ##
## Experiment with different values ##
## Strength is how much the player will be pushed forward ##
## Up is how much the player will be pushed in the air ##
## Have a nice day and enjoy the plugin ;) ##
## NoFallDamageTimeMob is applied only when the mob steps on the plate and it lasts for the time you define it in seconds ##
## Sound can be chosen from numbers 0-4, 0 means no sound ##
Strength: 2.0
Up: 1.1
mobUse: false
Sound: 1
NoFallDamageTimeMob: 3
UnlimitedPlates: false
help:
  - "&b      << -- PressurePush -- >>"
  - "&c&oPressurePush Version: {version} by euro1988 // Edited by CullanP"
  - "&a/ppcreate on  - toggles the creation of PressurePush plates to true"
  - "&a/ppcreate off  - toggles the creation of PressurePush plates to false"
  - "&a/ppload  - reloads the PressurePush config"